### ISSUE TITLE
Plays 'this is what slow speed sounds like' when translator is called

### ISSUE THREAD

**Issue by EshSub** [KoreanThinker/react-native-translator#21]
When <Translator> or useTranslator() is used, after the result is returned, an audio is played automatically saying 'this is what slow speed sounds like. How to solve this issue. Any help is much appreciated.

Also mentioned in this issue,

also the "eu policy" setInterval causes a sound in the "enter url" page 
it should check the url in injecetedscript

_Originally posted by @soroshzzz26 in https://github.com/KoreanThinker/react-native-translator/issues/18#issuecomment-1703905022_

version "react-native-translator": "^1.1.6",

**Comment by LouisSyfer** [comment]
Same issue. This package makes my app speaking.

**Comment by soroshzzz26** [comment]
- I think this package  doesent maintained anymore but i forked the package and fixed the bugs for my project
- https://github.com/soroshzzz26/react-native-translator
- you can check the commits

**Comment by LouisSyfer** [comment]
Hi @soroshzzz26 ! This looks interesting. But have you fixed all the bugs ? I also tested this package on another project and the application crashed...
