### ISSUE TITLE
Translator stopping the text at new lines and ";" 

### ISSUE THREAD

**Issue by decamps-enmanuel** [KoreanThinker/react-native-translator#7]
Hello, great lib. I'm stuck in an specific point. I'm trying to translate some text and the hook only returns the text until a special character is found.

Example:
**Input string:** La excursión en kayak es nuestra actividad más popular; una aventura relajante donde puedes recorrer 5km por un río de aguas color azul turquesa, hermosos bancos de arena, árboles centenarios, y un paisaje autentico, agradable, y romántica para las parejas, divertida para amigos y familiares.

**Output** : The kayak excursion is our most popular activity;

As you can see it stops right at the first ";".

Removing the special characters allows the hook to translate it all but it's dynamic text so I can't really start replacing special characters.

Any ideas?

**Comment by KoreanThinker** [comment]
Could you please show your code?

**Comment by KoreanThinker** [comment]
Is it not work?
```ts
const onTranslate = async () => {

    const result = await translate("es", "en", `${contentText.replace(/;/gi, "");}`, {
      type: "google",
      timeout: 10000,
    });
    console.log("translation result is", result);
};
```

**Comment by decamps-enmanuel** [comment]
If I replace that the content will lose the ";". The semi colon is not the only thing that's stopping the translator to stop.

**Comment by KoreanThinker** [comment]
1. remove `package.lock.json` & `node_modules`
2. remove `react-native-translator: "1.1.3"` from `package.json`
3. run `npm install`
4. run `npm i --save https://github.com/KoreanThinker/react-native-translator.git#url-encoding`

**Comment by KoreanThinker** [comment]
@decamps-enmanuel Are you resolved?

**Comment by KoreanThinker** [comment]
> im also facing this issue.. any updates?

I'm so busy... I think this is easy to resolve. Can you pull some request?
